### PR TITLE
fixes #92: add endpoints for readiness and liveness checks

### LINKED ISSUE #92: Add endpoints for readiness and liveness
Provide endpoints that can be used by orchestrators of auto-scalable environments, like Kubernetes. I'll mostly use Kubernetes definitions in this issue (taken from https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).

Many applications running for long periods of time eventually transition to broken states, and cannot recover except by being restarted. Kubernetes provides liveness probes to detect and remedy such situations. To facilitate such probes, our plugin should provide an endpoint that returns an HTTP Status code outside of the 200-399 range, when Openfire is in a state where it requires a restart. 

For liveness checks, these conditions come to mind:
- When a deadlock is detected: `ManagementFactory.getThreadMXBean().findDeadlockedThreads()` returns non-null.
- a system property that reports that a restart is required, after a change was applied. Caveat: this could lead to a scenario where a server is being restarted while property changes are being made.
- cache consistency checks. Caveat(s): we know that there are issues with these, and they may automatically recover.

Readiness probes are used to know when a container is ready to start accepting traffic. Sometimes, applications are temporarily unable to serve traffic. For example, an application might need to load large data or configuration files during startup, or depend on external services after startup. In such cases, you don't want to kill the application, but you don't want to send it requests either. Kubernetes provides readiness probes to detect and mitigate these situations. A pod with containers reporting that they are not ready does not receive traffic through Kubernetes Services.

For readiness checks, these conditions come to mind:
- All (non-disabled) Connection Managers are ready to accept data
- The plugin manager has finished executing its initial run to load all plugins upon boot
- `XmppServer.isStarted()` returns `true`
- When clustering is enabled, clustering reports 'ready'

### PR DESCRIPTION
**Pull request by guusdk**
Adds endpoints that perform checks for 'readiness' of Openfire (to accept data), and 'liveness' (to check if Openfire is in a state where it needs a reboot). See issue #92 for more details.

An endpoint is added for each individual check. Additionally, and endpoint has also been added that performs all checks of a particular type.

### CODE REVIEW

File: src/java/org/jivesoftware/openfire/plugin/rest/service/SystemService.java [hunk 1]
```diff
@@ -0,0 +1,274 @@
...
+        if (!SystemController.getInstance().hasPluginManagerExecuted()) {
+            return Response.status(Response.Status.SERVICE_UNAVAILABLE).build();
+        }
+        return Response.status(Response.Status.OK).build();
+    }
+
+    @GET
+    @Path("/readiness/connections")
+    @Operation( summary = "Perform 'connections' readiness check",
+        description = "Detects if Openfire is ready accepting connection requests.",
```
Comment (Fishbowler) [inline src/java/org/jivesoftware/openfire/plugin/rest/service/SystemService.java:246]: Typo

File: src/java/org/jivesoftware/openfire/plugin/rest/service/SystemService.java [hunk 2]
```diff
@@ -0,0 +1,274 @@
...
+        responses = {
+            @ApiResponse(responseCode = "200", description = "The system is ready."),
+            @ApiResponse(responseCode = "400", description = "The provided connectionType value is invalid."),
+            @ApiResponse(responseCode = "503", description = "Openfire currently does not accept (all) connections.")
+        })
+    public Response readinessConnections(
+        @Parameter(description = "Optional. Use to limit the check to one particular connection type. One of: SOCKET_S2S, SOCKET_C2S, BOSH_C2S, WEBADMIN, COMPONENT, CONNECTION_MANAGER", example = "SOCKET_C2S", required = false) @QueryParam("connectionType") String connectionType,
+        @Parameter(description = "Check the encrypted (true) or unencrypted (false) variant of the connection type. Only used in combination with 'connectionType'.", required = false) @QueryParam("servicename") Boolean encrypted
```
Comment (Fishbowler) [inline src/java/org/jivesoftware/openfire/plugin/rest/service/SystemService.java:254]: Should be QueryParam("encrypted") ?

File: src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java [hunk 3]
```diff
@@ -0,0 +1,273 @@
...
+            default:
+                final ConnectionManagerImpl connectionManager = (ConnectionManagerImpl) XMPPServer.getInstance().getConnectionManager();
+                if (connectionManager == null) {
+                    return false;
+                }
+                final ConnectionListener listener = connectionManager.getListener(connectionType, encrypted);
+                if (listener == null) {
+                    return false;
+                }
+                return !listener.isEnabled() || listener.getSocketAcceptor() != null;
```
Comment (Fishbowler) [inline src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java:253]: Is this logic correct?
If the listener is _not_ enabled OR if the listener has a MINA NioSocketAcceptor, then return True?
Feels like is should be: if it _is_ enabled (which defaults to true if it isn't configurable) AND has a MINA NioSocketAcceptor, then return True

File: src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java [hunk 4]
```diff
@@ -0,0 +1,273 @@
...
+     *
+     * @param connectionType The type of connection for which to check state
+     * @param encrypted true when the direct-TLS encrypted variant of the listeners is to be checked, otherwise false.
+     * @return True when the connection listener is ready to accept connections, or is disabled.
+     */
+    public boolean isConnectionListenerStartedWhenEnabled(@Nonnull final ConnectionType connectionType, final boolean encrypted) {
+        switch (connectionType) {
+            case BOSH_C2S:
+                if (encrypted) {
+                    return !HttpBindManager.HTTP_BIND_ENABLED.getValue() || HttpBindManager.HTTP_BIND_SECURE_PORT.getValue() <= 0 || HttpBindManager.getInstance().isHttpsBindActive();
```
Comment (Fishbowler) [inline src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java:231]:
```suggestion
                    return HttpBindManager.HTTP_BIND_ENABLED.getValue() && HttpBindManager.HTTP_BIND_SECURE_PORT.getValue() >= 0 && HttpBindManager.getInstance().isHttpsBindActive();
```

Should it be "If ALL these things are on / have good values"?

File: src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java [hunk 5]
```diff
@@ -0,0 +1,273 @@
...
+                } else {
+                    return !HttpBindManager.HTTP_BIND_ENABLED.getValue() || HttpBindManager.HTTP_BIND_PORT.getValue() <= 0 || HttpBindManager.getInstance().isHttpBindActive();
```
Comment (Fishbowler) [inline src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java:233]: As above

File: src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java [hunk 6]
```diff
@@ -0,0 +1,273 @@
...
+
+    /**
+     * Determine if clustering has been fully started, if clustering is enabled.
+     *
+     * When clustering is not enabled, this method will always return 'true'.
+     *
+     * @return true if Openfire has started, otherwise false.
+     */
+    public boolean hasClusteringStartedWhenEnabled() {
+        if (!ClusterManager.isClusteringEnabled()) {
```
Comment (Fishbowler) [inline src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java:202]: Is "enabled" enough for this readiness check? Does it need to be settled?

File: src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java (hunk 3 above)
Comment (guusdk) [reply src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java:253]: I did this on purpose. Putting it differently, when _disabled_, the listener immediately is in the state that we expect it to be in. My reasoning was as follows: if the listener is disabled, the check to see if it is 'ready' should pass. If the check does not pass when a listener is disabled, then this test will always indicate that the server isn't ready to be used.

I tried to give the method a name that reflects this, but I won't argue that it's confusing. Assuming that you agree with my logic, do you see a way to make things more logical?

File: src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java (hunk 4 above)
Comment (guusdk) [reply src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java:231]: I don't think so: if the connection type is disabled (either 'enabled == false' or the port number <= 0) then the check should always pass (otherwise, Openfire would never be 'ready').

File: src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java (hunk 5 above)
Comment (guusdk) [reply src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java:233]: As above. :)

File: src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java (hunk 6 above)
Comment (guusdk) [reply src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java:202]: This uses the same reasoning as earlier. You are right that we need to wait for clustering to be settled, but that's done in the next few lines. If clustering is _disabled_, then the check should report successful (as Openfire is 'ready to be used' from this perspective).

**Comment by guusdk** [comment]
Rebased to master.

File: src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java (hunk 3 above)
Comment (Fishbowler) [reply src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java:253]: That does make more sense.

**Review by Fishbowler — APPROVED** [review]

**Comment by Fishbowler** [comment]
You're absolutely right on all counts. I've pushed a few little text changes. If you don't hate them, merge away :+1:
